vich_uploader:
    db_driver: orm

    mappings:
       songs:
           uri_prefix: '%song_file%'
           upload_destination: '%kernel.project_dir%/public%song_file%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: false
           delete_on_remove: false
